public with sharing class Numbe9
{
    
        public static void generatePyramid() {

          Integer numbers = 1;

        for (Integer i = 1; i <= 4; i++) {

         for (Integer j = 1; j <= i; j++) {

           System.debug(numbers);

        numbers++;

    }

    System.debug('\n');

}

}


 


public static void reverseOrder(String name)

    {

        string reverseName=name.reverse();

        system.debug(reverseName);

    }}




    




